### PR TITLE
#29 Backend implementation (Save record)

### PR DESCRIPTION
**Pull request by Electryk**
#29 
Added "isValidxxx" methods for each field to check (only for "saveRecord" fields at this moment).
"saveRecord" servlet redirects to "listPerformed" if all is correct.

### CODE REVIEW

**Comment by Electryk** [comment]
Maybe all not are common to the servlets, but an hipotethic "isValidUser" serves for signIn and signUp

**Comment by Gascon95** [comment]
Then, you will implement those methods on ServletCommon. But those three you have implemented, are specific to the SaveRecord servlet. I don't see the point of having them on ServetCommon.

**Comment by Electryk** [comment]
Scalability. These methods provide funcionality at common fields in the app. Filters can use these too, for example

**Comment by Gascon95** [comment]
You mean "reusability"? Scalability has nothing to do with this. Do you mind to tell us what "fields in the app" do you mean? And, by the way, filters are implemented in the frontend.

**Pull request merged**
